//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Console.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class productimage
    {
        public long Id { get; set; }
        public long VendorProductId { get; set; }
        public string ImagePath { get; set; }
        public string ImageType { get; set; }
    
        public virtual vendorproduct vendorproduct { get; set; }
    }
}
