//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Console.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class productfileconfig
    {
        public long Id { get; set; }
        public int VendorId { get; set; }
        public Nullable<int> SKU { get; set; }
        public Nullable<int> Name { get; set; }
        public Nullable<int> Description { get; set; }
        public Nullable<int> ShortDescription { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> UPCCode { get; set; }
        public Nullable<int> SupplierCost { get; set; }
    
        public virtual vendor vendor { get; set; }
    }
}
