//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Console.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendorproduct
    {
        public vendorproduct()
        {
            this.productimages = new HashSet<productimage>();
        }
    
        public long Id { get; set; }
        public int VendorId { get; set; }
        public string SKU { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public string Category { get; set; }
        public string UPCCode { get; set; }
        public decimal SupplierCost { get; set; }
        public System.DateTime ResultDate { get; set; }
    
        public virtual ICollection<productimage> productimages { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
