//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Console.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public vendor()
        {
            this.imagefileconfigs = new HashSet<imagefileconfig>();
            this.productfileconfigs = new HashSet<productfileconfig>();
            this.uploadstatus = new HashSet<uploadstatu>();
            this.vendorproducts = new HashSet<vendorproduct>();
        }
    
        public int Id { get; set; }
        public string VendorName { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string TransferPath { get; set; }
        public string EISSKUCode { get; set; }
        public System.TimeSpan UploadTime { get; set; }
        public System.TimeSpan ReadTime { get; set; }
        public Nullable<int> RowAt { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> NextRunTime { get; set; }
    
        public virtual ICollection<imagefileconfig> imagefileconfigs { get; set; }
        public virtual ICollection<productfileconfig> productfileconfigs { get; set; }
        public virtual ICollection<uploadstatu> uploadstatus { get; set; }
        public virtual ICollection<vendorproduct> vendorproducts { get; set; }
    }
}
