//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class amazoncredential : credential
    {
        public string MerchantId { get; set; }
        public string AccessKeyId { get; set; }
        public string SecretKey { get; set; }
        public string AssociateId { get; set; }
        public string SearchAccessKeyId { get; set; }
        public string SearchSecretKey { get; set; }
    }
}
