//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class amazonmwssetting
    {
        public int Id { get; set; }
        public string MarketplaceMode { get; set; }
        public string MerchantId { get; set; }
        public string AccessKeyId { get; set; }
        public string SecretKey { get; set; }
        public string DeveloperId { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string MarketplaceIds { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
