//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class amazoncategory
    {
        public amazoncategory()
        {
            this.amazonsubcategories = new HashSet<amazonsubcategory>();
            this.producttypes = new HashSet<producttype>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string ClassName { get; set; }
    
        public virtual ICollection<amazonsubcategory> amazonsubcategories { get; set; }
        public virtual ICollection<producttype> producttypes { get; set; }
    }
}
