//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnetrole
    {
        public aspnetrole()
        {
            this.aspnetusers = new HashSet<aspnetuser>();
            this.applicationgroups = new HashSet<applicationgroup>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<aspnetuser> aspnetusers { get; set; }
        public virtual ICollection<applicationgroup> applicationgroups { get; set; }
    }
}
