//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bigcommercecustomfield
    {
        public int Id { get; set; }
        public Nullable<int> CustomFieldId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
    }
}
