//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.credentials = new HashSet<credential>();
            this.vendors = new HashSet<vendor>();
            this.marketplaceinventorytasks = new HashSet<marketplaceinventorytask>();
            this.products = new HashSet<product>();
            this.customers = new HashSet<customer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Currency { get; set; }
        public string Abbreviation { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public bool IsDefault { get; set; }
        public string SKUCodeStart { get; set; }
        public string SearialSKUCode { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual ICollection<credential> credentials { get; set; }
        public virtual ICollection<vendor> vendors { get; set; }
        public virtual ICollection<marketplaceinventorytask> marketplaceinventorytasks { get; set; }
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<customer> customers { get; set; }
    }
}
