//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class credential
    {
        public int Id { get; set; }
        public string Mode { get; set; }
        public string Name { get; set; }
        public string MarketplaceType { get; set; }
        public string MarketplaceId { get; set; }
        public int CompanyId { get; set; }
        public bool IsEnabled { get; set; }
        public string ServiceEndPoint { get; set; }
        public bool IsDefault { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual company company { get; set; }
    }
}
