//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerexportedfile
    {
        public long Id { get; set; }
        public int ScheduledTaskId { get; set; }
        public string FileName { get; set; }
        public Nullable<long> FileSize { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual customerscheduledtask customerscheduledtask { get; set; }
    }
}
