//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerwholesalepricehistory
    {
        public int Id { get; set; }
        public string EisSKU { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> CustomerScheduleId { get; set; }
        public decimal SkuCalculatedPrice { get; set; }
        public string ModifiedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public System.DateTime Created { get; set; }
    }
}
