//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.customerimages = new HashSet<customerimage>();
            this.customersaddresses = new HashSet<customersaddress>();
            this.customersnotes = new HashSet<customersnote>();
            this.customerscheduledtasks = new HashSet<customerscheduledtask>();
        }
    
        public int CustomerId { get; set; }
        public int CustomerNumber { get; set; }
        public string CompanyName { get; set; }
        public int CompanyId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string OfficeNumber { get; set; }
        public int AccountType { get; set; }
        public Nullable<decimal> CostPlusBasedWholeSalePrice { get; set; }
        public Nullable<int> CostPlusBasedWholeSalePriceType { get; set; }
        public Nullable<int> CreditLimit { get; set; }
        public Nullable<int> CreditTerms { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> AmountType { get; set; }
    
        public virtual company company { get; set; }
        public virtual ICollection<customerimage> customerimages { get; set; }
        public virtual ICollection<customersaddress> customersaddresses { get; set; }
        public virtual ICollection<customersnote> customersnotes { get; set; }
        public virtual ICollection<customerscheduledtask> customerscheduledtasks { get; set; }
    }
}
