//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.vendordepartments = new HashSet<vendordepartment>();
        }
    
        public int Id { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual ICollection<vendordepartment> vendordepartments { get; set; }
    }
}
