//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebaycredential : credential
    {
        public string ApplicationId { get; set; }
        public string DeveloperId { get; set; }
        public string CertificationId { get; set; }
        public string UserToken { get; set; }
        public Nullable<int> DescriptionTemplateId { get; set; }
        public string PayPalEmailAddress { get; set; }
    
        public virtual messagetemplate messagetemplate { get; set; }
    }
}
