//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebaysubcategory
    {
        public ebaysubcategory()
        {
            this.producttypes = new HashSet<producttype>();
        }
    
        public string Id { get; set; }
        public string CategoryName { get; set; }
        public int CategoryLevel { get; set; }
        public string CategoryParentId { get; set; }
        public bool IsLeaf { get; set; }
        public bool IsBestOfferEnabled { get; set; }
        public bool IsAutoPayEnabled { get; set; }
    
        public virtual ebaycategory ebaycategory { get; set; }
        public virtual ICollection<producttype> producttypes { get; set; }
    }
}
