//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EisInventoryContext : DbContext
    {
        public EisInventoryContext()
            : base("name=EisInventoryContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<amazoncategory> amazoncategories { get; set; }
        public DbSet<amazonmwssetting> amazonmwssettings { get; set; }
        public DbSet<amazonsubcategory> amazonsubcategories { get; set; }
        public DbSet<aspnetrole> aspnetroles { get; set; }
        public DbSet<aspnetuserclaim> aspnetuserclaims { get; set; }
        public DbSet<aspnetuserlogin> aspnetuserlogins { get; set; }
        public DbSet<aspnetuser> aspnetusers { get; set; }
        public DbSet<country> countries { get; set; }
        public DbSet<orderitem> orderitems { get; set; }
        public DbSet<ordershipment> ordershipments { get; set; }
        public DbSet<processingreportresult> processingreportresults { get; set; }
        public DbSet<processingreport> processingreports { get; set; }
        public DbSet<producttypecategorymapping> producttypecategorymappings { get; set; }
        public DbSet<purchaseorder> purchaseorders { get; set; }
        public DbSet<region> regions { get; set; }
        public DbSet<requestreport> requestreports { get; set; }
        public DbSet<producttype> producttypes { get; set; }
        public DbSet<productimage> productimages { get; set; }
        public DbSet<productgroupdetail> productgroupdetails { get; set; }
        public DbSet<purchaseorderitem> purchaseorderitems { get; set; }
        public DbSet<log> logs { get; set; }
        public DbSet<orderupdatehistory> orderupdatehistories { get; set; }
        public DbSet<kitdetail> kitdetails { get; set; }
        public DbSet<kit> kits { get; set; }
        public DbSet<shadow> shadows { get; set; }
        public DbSet<settlementorderitemfee> settlementorderitemfees { get; set; }
        public DbSet<settlementorderitemprice> settlementorderitemprices { get; set; }
        public DbSet<settlementorderitem> settlementorderitems { get; set; }
        public DbSet<settlementorder> settlementorders { get; set; }
        public DbSet<settlementrefunditemfee> settlementrefunditemfees { get; set; }
        public DbSet<settlementrefunditemprice> settlementrefunditemprices { get; set; }
        public DbSet<settlementrefunditem> settlementrefunditems { get; set; }
        public DbSet<settlementrefund> settlementrefunds { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<credential> credentials { get; set; }
        public DbSet<ebaycategory> ebaycategories { get; set; }
        public DbSet<ebaysubcategory> ebaysubcategories { get; set; }
        public DbSet<shippingstationtracking> shippingstationtrackings { get; set; }
        public DbSet<postingfee> postingfees { get; set; }
        public DbSet<ordershipmenthistory> ordershipmenthistories { get; set; }
        public DbSet<productamazon> productamazons { get; set; }
        public DbSet<productebay> productebays { get; set; }
        public DbSet<ebaystructuredcategory> ebaystructuredcategories { get; set; }
        public DbSet<department> departments { get; set; }
        public DbSet<vendordepartment> vendordepartments { get; set; }
        public DbSet<reporttemplate> reporttemplates { get; set; }
        public DbSet<shippingrate> shippingrates { get; set; }
        public DbSet<messagetemplate> messagetemplates { get; set; }
        public DbSet<exportedfile> exportedfiles { get; set; }
        public DbSet<vendor> vendors { get; set; }
        public DbSet<scheduledtask> scheduledtasks { get; set; }
        public DbSet<inventoryvendorproduct> inventoryvendorproducts { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<applicationgroup> applicationgroups { get; set; }
        public DbSet<systemjob> systemjobs { get; set; }
        public DbSet<orderproduct> orderproducts { get; set; }
        public DbSet<vendorproductlink> vendorproductlinks { get; set; }
        public DbSet<vendorproduct> vendorproducts { get; set; }
        public DbSet<productbigcommerce> productbigcommerces { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<ordergroupdetail> ordergroupdetails { get; set; }
        public DbSet<bigcommercebrand> bigcommercebrands { get; set; }
        public DbSet<bigcommercecustomfield> bigcommercecustomfields { get; set; }
        public DbSet<addressdetail> addressdetails { get; set; }
        public DbSet<shippinglocation> shippinglocations { get; set; }
        public DbSet<vendorproductimage> vendorproductimages { get; set; }
        public DbSet<systememail> systememails { get; set; }
        public DbSet<savedsearchfilter> savedsearchfilters { get; set; }
        public DbSet<customerimage> customerimages { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<scheduletaskimportfile> scheduletaskimportfiles { get; set; }
        public DbSet<customersaddress> customersaddresses { get; set; }
        public DbSet<customersnote> customersnotes { get; set; }
        public DbSet<bigcommercecategory> bigcommercecategories { get; set; }
        public DbSet<customerwholesalepricehistory> customerwholesalepricehistories { get; set; }
        public DbSet<customerexportedfile> customerexportedfiles { get; set; }
        public DbSet<customerscheduledtask> customerscheduledtasks { get; set; }
    }
}
