//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class generatepotask : scheduledtask
    {
        public int VendorId { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string ExportTo { get; set; }
        public bool MarkPoGenerated { get; set; }
        public string EmailSubject { get; set; }
        public string EmailTo { get; set; }
        public string EmailCc { get; set; }
        public string FtpServer { get; set; }
        public string FtpUser { get; set; }
        public string FtpPassword { get; set; }
        public Nullable<int> FtpPort { get; set; }
        public string RemoteFolder { get; set; }
    
        public virtual vendor vendor { get; set; }
    }
}
