//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryvendorproduct
    {
        public long Id { get; set; }
        public int VendorId { get; set; }
        public string SupplierSKU { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SupplierPrice { get; set; }
        public string UPC { get; set; }
        public Nullable<int> MinPack { get; set; }
        public System.DateTime ResultDate { get; set; }
    }
}
