//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitdetail
    {
        public string ParentKitSKU { get; set; }
        public string ChildKitSKU { get; set; }
        public bool IsMain { get; set; }
        public int Quantity { get; set; }
    
        public virtual kit kit { get; set; }
        public virtual product product { get; set; }
    }
}
