//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public System.DateTime Created { get; set; }
        public int Severity { get; set; }
        public int EntryType { get; set; }
        public string Description { get; set; }
        public string StackTrace { get; set; }
        public int Id { get; set; }
    }
}
