//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class marketplaceinventorytask : scheduledtask
    {
        public int CompanyId { get; set; }
        public string Marketplaces { get; set; }
    
        public virtual company company { get; set; }
    }
}
