//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class messagetemplate
    {
        public messagetemplate()
        {
            this.ebaycredentials = new HashSet<ebaycredential>();
        }
    
        public int Id { get; set; }
        public EIS.Inventory.Shared.Models.MessageType MessageType { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string ContentHtml { get; set; }
        public bool IsEnabled { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> SystemEmailId { get; set; }
    
        public virtual ICollection<ebaycredential> ebaycredentials { get; set; }
        public virtual systememail systememail { get; set; }
    }
}
