//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderitems = new HashSet<orderitem>();
            this.ordergroupdetails = new HashSet<ordergroupdetail>();
        }
    
        public int EisOrderId { get; set; }
        public string OrderId { get; set; }
        public string Marketplace { get; set; }
        public decimal OrderTotal { get; set; }
        public Nullable<int> NumOfItemsShipped { get; set; }
        public Nullable<int> NumOfItemsUnshipped { get; set; }
        public EIS.Inventory.Shared.Models.OrderStatus OrderStatus { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string PaymentMethod { get; set; }
        public string BuyerName { get; set; }
        public string BuyerEmail { get; set; }
        public string ShippingAddressPhone { get; set; }
        public string ShippingAddressName { get; set; }
        public string ShippingAddressLine1 { get; set; }
        public string ShippingAddressLine2 { get; set; }
        public string ShippingAddressLine3 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingStateOrRegion { get; set; }
        public string ShippingPostalCode { get; set; }
        public string ShipServiceLevel { get; set; }
        public string ShipmentServiceCategory { get; set; }
        public Nullable<System.DateTime> EarliestShipDate { get; set; }
        public Nullable<System.DateTime> LatestShipDate { get; set; }
        public Nullable<System.DateTime> EarliestDeliveryDate { get; set; }
        public Nullable<System.DateTime> LatestDeliveryDate { get; set; }
        public string OrderType { get; set; }
        public string SellerOrderId { get; set; }
        public string MarketplaceId { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string SalesChannel { get; set; }
        public Nullable<decimal> AdjustmentAmount { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> PaymentOrRefundAmount { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string CarrierCode { get; set; }
        public string ShippingMethod { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<decimal> ShipmentCost { get; set; }
        public int PaymentStatus { get; set; }
        public string OrderNote { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CompanyName { get; set; }
    
        public virtual ICollection<orderitem> orderitems { get; set; }
        public virtual ordershipmenthistory ordershipmenthistory { get; set; }
        public virtual ICollection<ordergroupdetail> ordergroupdetails { get; set; }
    }
}
