//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordershipment
    {
        public int Id { get; set; }
        public string Marketplace { get; set; }
        public string OrderId { get; set; }
        public string CarrierCode { get; set; }
        public string ShippingMethod { get; set; }
        public System.DateTime ShipDate { get; set; }
        public Nullable<bool> IsSucceed { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public System.DateTime Created { get; set; }
    }
}
