//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class processingreportresult
    {
        public long Id { get; set; }
        public string TransactionId { get; set; }
        public int MessageId { get; set; }
        public string Code { get; set; }
        public string MessageCode { get; set; }
        public string AdditionalInfo { get; set; }
        public string Description { get; set; }
    }
}
