//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.kitdetails = new HashSet<kitdetail>();
            this.productimages = new HashSet<productimage>();
            this.shadows = new HashSet<shadow>();
            this.vendorproductlinks = new HashSet<vendorproductlink>();
            this.productgroupdetails = new HashSet<productgroupdetail>();
            this.shadows1 = new HashSet<shadow>();
        }
    
        public string EisSKU { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public string Category { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public string UPC { get; set; }
        public decimal SellerPrice { get; set; }
        public Nullable<decimal> PkgLength { get; set; }
        public Nullable<decimal> PkgWidth { get; set; }
        public Nullable<decimal> PkgHeight { get; set; }
        public string PkgLenghtUnit { get; set; }
        public Nullable<decimal> ItemLength { get; set; }
        public Nullable<decimal> ItemWidth { get; set; }
        public Nullable<decimal> ItemHeight { get; set; }
        public string ItemLenghtUnit { get; set; }
        public Nullable<decimal> PkgWeight { get; set; }
        public string PkgWeightUnit { get; set; }
        public Nullable<decimal> ItemWeight { get; set; }
        public string ItemWeightUnit { get; set; }
        public string EAN { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> GuessedWeight { get; set; }
        public string GuessedWeightUnit { get; set; }
        public Nullable<decimal> AccurateWeight { get; set; }
        public string AccurateWeightUnit { get; set; }
        public Nullable<decimal> Weight_1 { get; set; }
        public Nullable<decimal> Weight_2 { get; set; }
        public Nullable<decimal> Weight_3 { get; set; }
        public Nullable<decimal> Weight_4 { get; set; }
        public Nullable<decimal> Weight_5 { get; set; }
        public string GuessedShipping { get; set; }
        public string AccurateShipping { get; set; }
        public bool IsKit { get; set; }
        public bool IsBlacklisted { get; set; }
        public EIS.Inventory.Shared.Models.SkuType SkuType { get; set; }
        public string Features { get; set; }
        public string ModifiedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual company company { get; set; }
        public virtual ICollection<kitdetail> kitdetails { get; set; }
        public virtual kit kit { get; set; }
        public virtual productamazon productamazon { get; set; }
        public virtual productbigcommerce productbigcommerce { get; set; }
        public virtual productebay productebay { get; set; }
        public virtual ICollection<productimage> productimages { get; set; }
        public virtual producttype producttype { get; set; }
        public virtual ICollection<shadow> shadows { get; set; }
        public virtual ICollection<vendorproductlink> vendorproductlinks { get; set; }
        public virtual ICollection<productgroupdetail> productgroupdetails { get; set; }
        public virtual ICollection<shadow> shadows1 { get; set; }
    }
}
