//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class productimage
    {
        public long Id { get; set; }
        public string EisSKU { get; set; }
        public string FileName { get; set; }
        public string ImageType { get; set; }
        public string Caption { get; set; }
        public string Marketplace { get; set; }
        public int Order_ { get; set; }
    
        public virtual product product { get; set; }
    }
}
