//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class productbigcommerce
    {
        public string EisSKU { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Condition { get; set; }
        public string Categories { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public string PrimaryImage { get; set; }
        public Nullable<decimal> FixedCostShippingPrice { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<int> ProductsType { get; set; }
        public Nullable<int> InventoryLevel { get; set; }
        public Nullable<int> InventoryWarningLevel { get; set; }
        public Nullable<int> InventoryTracking { get; set; }
        public Nullable<int> OrderQuantityMinimum { get; set; }
        public Nullable<int> OrderQuantityMaximum { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ProductURL { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        public virtual product product { get; set; }
    }
}
