//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class productebay
    {
        public string EisSKU { get; set; }
        public string ItemId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public decimal StartPrice { get; set; }
        public decimal ReservePrice { get; set; }
        public decimal BinPrice { get; set; }
        public string ListType { get; set; }
        public string Duration { get; set; }
        public string Location { get; set; }
        public int Condition_ { get; set; }
        public int ListingQuantity { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SafetyQty { get; set; }
        public int DispatchTimeMax { get; set; }
        public bool IsBoldTitle { get; set; }
        public bool IsOutOfStockListing { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsRequireAutoPayment { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> EndedItemDate { get; set; }
        public Nullable<System.DateTime> ReListedItemDate { get; set; }
    
        public virtual ebaystructuredcategory ebaystructuredcategory { get; set; }
        public virtual product product { get; set; }
    }
}
