//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class producttype
    {
        public producttype()
        {
            this.products = new HashSet<product>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string AmazonMainCategoryCode { get; set; }
        public string AmazonSubCategoryCode { get; set; }
        public string EbayMainCategoryCode { get; set; }
        public string EbaySubCategoryCode { get; set; }
    
        public virtual amazoncategory amazoncategory { get; set; }
        public virtual amazonsubcategory amazonsubcategory { get; set; }
        public virtual producttypecategorymapping producttypecategorymapping { get; set; }
        public virtual ebaycategory ebaycategory { get; set; }
        public virtual ebaysubcategory ebaysubcategory { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
