//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class productamazon
    {
        public string EisSKU { get; set; }
        public Nullable<int> LeadtimeShip { get; set; }
        public Nullable<int> PackageQty { get; set; }
        public Nullable<int> NumOfItems { get; set; }
        public Nullable<int> MaxOrderQty { get; set; }
        public string ProductTitle { get; set; }
        public Nullable<decimal> MapPrice { get; set; }
        public Nullable<bool> IsAllowGiftWrap { get; set; }
        public Nullable<bool> IsAllowGiftMsg { get; set; }
        public string Condition { get; set; }
        public string ConditionNote { get; set; }
        public string FulfilledBy { get; set; }
        public string FbaSKU { get; set; }
        public string ProductGroup { get; set; }
        public string ProductTypeName { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> SafetyQty { get; set; }
        public Nullable<decimal> WeightBox1 { get; set; }
        public string WeightBox1Unit { get; set; }
        public Nullable<decimal> WeightBox2 { get; set; }
        public string WeightBox2Unit { get; set; }
        public string ASIN { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ModifiedBy { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual product product { get; set; }
    }
}
