//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseorder
    {
        public purchaseorder()
        {
            this.purchaseorderitems = new HashSet<purchaseorderitem>();
        }
    
        public string Id { get; set; }
        public int VendorId { get; set; }
        public EIS.Inventory.Shared.Models.PaymentStatus PaymentStatus { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsManual { get; set; }
    
        public virtual ICollection<purchaseorderitem> purchaseorderitems { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
