//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporttemplate
    {
        public int Id { get; set; }
        public string FileFormat { get; set; }
        public string SortField { get; set; }
        public string Fields { get; set; }
        public string Name { get; set; }
        public string Discriminator { get; set; }
    }
}
