//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestreport
    {
        public int Id { get; set; }
        public string RequestId { get; set; }
        public string ReportRequestId { get; set; }
        public string FeedType { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ProcessingStatus { get; set; }
        public bool IsScheduled { get; set; }
        public string SubmittedDate { get; set; }
        public string SubmittedBy { get; set; }
    }
}
