//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class savedsearchfilter
    {
        public int Id { get; set; }
        public int SavedSearchFilterId { get; set; }
        public string SavedSearchFilterName { get; set; }
        public string SearchString { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
    }
}
