//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduledtask
    {
        public scheduledtask()
        {
            this.exportedfiles = new HashSet<exportedfile>();
            this.scheduletaskimportfiles = new HashSet<scheduletaskimportfile>();
        }
    
        public int Id { get; set; }
        public string TaskType { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public Nullable<System.DateTime> LastExecutedOn { get; set; }
        public bool IsRunNow { get; set; }
        public string Recurrence { get; set; }
        public int OccurrAt { get; set; }
        public string Days { get; set; }
        public int History { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<exportedfile> exportedfiles { get; set; }
        public virtual ICollection<scheduletaskimportfile> scheduletaskimportfiles { get; set; }
    }
}
