//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class settlementorderitem
    {
        public settlementorderitem()
        {
            this.settlementorderitemfees = new HashSet<settlementorderitemfee>();
            this.settlementorderitemprices = new HashSet<settlementorderitemprice>();
        }
    
        public string OrderItemCode { get; set; }
        public string OrderId { get; set; }
        public string SKU { get; set; }
        public int Quantity { get; set; }
    
        public virtual ICollection<settlementorderitemfee> settlementorderitemfees { get; set; }
        public virtual ICollection<settlementorderitemprice> settlementorderitemprices { get; set; }
        public virtual settlementorder settlementorder { get; set; }
    }
}
