//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class settlementorderitemfee
    {
        public string OrderItemCode { get; set; }
        public string FeeType { get; set; }
        public string CurrencyCode { get; set; }
        public decimal Amount { get; set; }
    
        public virtual settlementorderitem settlementorderitem { get; set; }
    }
}
