//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class settlementrefund
    {
        public settlementrefund()
        {
            this.settlementrefunditems = new HashSet<settlementrefunditem>();
        }
    
        public string OrderId { get; set; }
        public string Marketplace { get; set; }
        public string AdjustmentId { get; set; }
        public string MerchantFulfillmentId { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string SettlementId { get; set; }
    
        public virtual ICollection<settlementrefunditem> settlementrefunditems { get; set; }
    }
}
