//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class settlementrefunditem
    {
        public settlementrefunditem()
        {
            this.settlementrefunditemfees = new HashSet<settlementrefunditemfee>();
            this.settlementrefunditemprices = new HashSet<settlementrefunditemprice>();
        }
    
        public string OrderItemCode { get; set; }
        public string OrderId { get; set; }
        public string SKU { get; set; }
        public string MerchantAdjustmentItemId { get; set; }
    
        public virtual ICollection<settlementrefunditemfee> settlementrefunditemfees { get; set; }
        public virtual ICollection<settlementrefunditemprice> settlementrefunditemprices { get; set; }
        public virtual settlementrefund settlementrefund { get; set; }
    }
}
