//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class shadow
    {
        public string ParentSKU { get; set; }
        public string ShadowSKU { get; set; }
        public int FactorQuantity { get; set; }
        public bool IsConnected { get; set; }
    
        public virtual product product { get; set; }
        public virtual product product1 { get; set; }
    }
}
