//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class shippingstationtracking
    {
        public int Id { get; set; }
        public int EisOrderId { get; set; }
        public Nullable<int> ShippingStationOrderId { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
