//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class shippinglocation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FromCompanyName { get; set; }
        public string FromPhone { get; set; }
        public int FromAddressId { get; set; }
        public string ReturnCompanyName { get; set; }
        public string ReturnPhone { get; set; }
        public int ReturnAddressId { get; set; }
        public bool IsReturnSame { get; set; }
        public bool IsDefault { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual addressdetail FromAddressDetails { get; set; }
        public virtual addressdetail ReturnAddressDetails { get; set; }
    }
}
