//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class shippingrate
    {
        public int Id { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> WeightFrom { get; set; }
        public Nullable<int> WeightTo { get; set; }
    }
}
