//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public vendor()
        {
            this.purchaseorders = new HashSet<purchaseorder>();
            this.vendordepartments = new HashSet<vendordepartment>();
            this.generatepotasks = new HashSet<generatepotask>();
            this.vendorproducts = new HashSet<vendorproduct>();
            this.vendorproductfileinventorytasks = new HashSet<vendorproductfileinventorytask>();
            this.customexportordertasks = new HashSet<customexportordertask>();
        }
    
        public int Id { get; set; }
        public string SKUCodeStart { get; set; }
        public string Name { get; set; }
        public string VendorAddress { get; set; }
        public string SuiteApartment { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int CompanyId { get; set; }
        public int SafetyQty { get; set; }
        public EIS.Inventory.Shared.Models.DropShipFeeType DropShipFeeType { get; set; }
        public Nullable<decimal> DropShipFee { get; set; }
        public string ReturnsAcceptedOption { get; set; }
        public string RefundOption { get; set; }
        public string ReturnsWithinOption { get; set; }
        public string ShippingCostPaidByOption { get; set; }
        public string ReturnPolicyDescription { get; set; }
        public string ShippingType { get; set; }
        public string ShippingService { get; set; }
        public decimal ShippingServiceCost { get; set; }
        public string State { get; set; }
        public string Website { get; set; }
        public string FaxField { get; set; }
        public string AvailableCarrier { get; set; }
        public string PickupFrequency { get; set; }
        public string ReturnPolicy { get; set; }
        public Nullable<int> DaysToReturn { get; set; }
        public string ContactName { get; set; }
        public string ShipFromAddress { get; set; }
        public string ShipInfoCity { get; set; }
        public string ShipInfoState { get; set; }
        public string ShipInfoZipCode { get; set; }
        public string ShipInfoPhone { get; set; }
        public string PaymentTerms { get; set; }
        public string CreditLimit { get; set; }
        public string InventoryUpdateFrequency { get; set; }
        public Nullable<int> AlwaysQuantity { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> ShippingMethod { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ModifiedBy { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual company company { get; set; }
        public virtual ICollection<purchaseorder> purchaseorders { get; set; }
        public virtual ICollection<vendordepartment> vendordepartments { get; set; }
        public virtual ICollection<generatepotask> generatepotasks { get; set; }
        public virtual ICollection<vendorproduct> vendorproducts { get; set; }
        public virtual ICollection<vendorproductfileinventorytask> vendorproductfileinventorytasks { get; set; }
        public virtual ICollection<customexportordertask> customexportordertasks { get; set; }
    }
}
