//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Inventory.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendorproduct
    {
        public vendorproduct()
        {
            this.orderproducts = new HashSet<orderproduct>();
            this.vendorproductlinks = new HashSet<vendorproductlink>();
            this.vendorproductimages = new HashSet<vendorproductimage>();
        }
    
        public string EisSupplierSKU { get; set; }
        public string SupplierSKU { get; set; }
        public int VendorId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal SupplierPrice { get; set; }
        public int Quantity { get; set; }
        public int MinPack { get; set; }
        public int TotalItems { get; set; }
        public string UPC { get; set; }
        public string Category { get; set; }
        public string Weight { get; set; }
        public string WeightUnit { get; set; }
        public string Shipping { get; set; }
        public Nullable<int> VendorMOQ { get; set; }
        public string VendorMOQType { get; set; }
        public string Status { get; set; }
        public bool IsAutoLinkToEisSKU { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public string ShortDescription { get; set; }
    
        public virtual ICollection<orderproduct> orderproducts { get; set; }
        public virtual ICollection<vendorproductlink> vendorproductlinks { get; set; }
        public virtual vendor vendor { get; set; }
        public virtual ICollection<vendorproductimage> vendorproductimages { get; set; }
    }
}
