using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EIS.Inventory.Shared.Models.Shippings
{
    public class EisShipmentSpecialServicesRequested
    {
        public List<EisShipmentSpecialServiceType> SpecialServiceTypes;

        public EisCodDetail CodDetail;
    }

    public enum EisShipmentSpecialServiceType
    {
        BROKER_SELECT_OPTION, CALL_BEFORE_DELIVERY, COD, CUSTOM_DELIVERY_WINDOW, CUT_FLOWERS, DANGEROUS_GOODS, DELIVERY_ON_INVOICE_ACCEPTANCE,
        DO_NOT_BREAK_DOWN_PALLETS, DO_NOT_STACK_PALLETS, DRY_ICE, EAST_COAST_SPECIAL, ELECTRONIC_TRADE_DOCUMENTS, EVENT_NOTIFICATION,
        EXTREME_LENGTH, FEDEX_ONE_RATE, FOOD, FREIGHT_GUARANTEE, FREIGHT_TO_COLLECT, FUTURE_DAY_SHIPMENT, HOLD_AT_LOCATION, HOME_DELIVERY_PREMIUM,
        INSIDE_DELIVERY, INSIDE_PICKUP, INTERNATIONAL_CONTROLLED_EXPORT_SERVICE, INTERNATIONAL_TRAFFIC_IN_ARMS_REGULATIONS, LIFTGATE_DELIVERY,
        LIFTGATE_PICKUP, LIMITED_ACCESS_DELIVERY, LIMITED_ACCESS_PICKUP, PENDING_SHIPMENT, PHARMACY_DELIVERY, POISON, PROTECTION_FROM_FREEZING, RETURNS_CLEARANCE,
        RETURN_SHIPMENT, SATURDAY_DELIVERY, SATURDAY_PICKUP, THIRD_PARTY_CONSIGNEE, TOP_LOAD
    }
}
